[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gradio_sidebar"
version = "0.0.1"
description = "A sidebar for Gradio applications"
readme = "README.md"
requires-python = ">=3.6"
license = {text = "MIT"}
authors = [
  {name = "Broadfield Dev"}
]
dependencies = [
  "gradio",
]

[project.urls]
"Homepage" = "https://github.com/broadfield-dev/gradio_sidebar"
